#!/usr/bin/env bash
#
# infra/preview/render-env.sh: render the per-PR env file an OSS preview stack needs.
#
# Ported in spirit from spiculedata/saiku-cloud infra/preview/render-env.sh
# (spiculedata/saiku-cloud#1378); the OSS stack is one container, so far less is
# rendered. Produces everything `docker compose` needs that is specific to ONE PR:
#
#   COMPOSE_PROJECT_NAME=saiku-oss-pr-<n>   own project -> own network + volume,
#                                           disjoint from the cloud's saiku-pr-<n>
#   SAIKU_IMAGE                             ghcr.io/spiculedata/saiku:<7-hex tag>, the
#                                           per-SHA tag docker.yml publishes. Never
#                                           `latest`, `development` or `pr-<n>`: those
#                                           move, and two PRs would overwrite each other
#   PREVIEW_HOST / ORIGIN                   oss-pr-<n>.<base domain> (one label under the
#                                           base, covered by the wildcard certificate)
#   SAIKU_ADMIN_PASSWORD                    random per environment, kept STABLE across
#                                           re-renders of the same file (a refresh must not
#                                           rotate a validator's credential); a teardown
#                                           deletes the file, so a new stack gets a new one
#
# Usage:
#   render-env.sh <pr-number> [--sha <sha>] [--image-tag T] [--base-domain D] [--out <file>]
#
# <pr-number> is a positive integer (anything else is refused: the number is the only
# thing the project name and hostname are derived from). T is a 7-hex per-SHA tag;
# without --image-tag it defaults to the first 7 hex of --sha (or is refused when --sha
# is not a hex sha). D is a DNS name (default preview.saiku.bi, or $PREVIEW_BASE_DOMAIN).
# Defaults: --sha $GITHUB_SHA, --out /tmp/<project>.env. Prints the path it wrote.
#
# Any value already exported in the environment WINS over the generated one
# (SAIKU_ADMIN_PASSWORD, PREVIEW_HOST), which is how a developer overrides it locally.

set -euo pipefail

PR=""
SHA="${GITHUB_SHA:-}"
TAG=""
DOMAIN="${PREVIEW_BASE_DOMAIN:-preview.saiku.bi}"
OUT=""
IMAGE_REGISTRY="${IMAGE_REGISTRY:-ghcr.io/spiculedata}"
IMAGE_REPOSITORY=saiku

usage() {
	echo "usage: render-env.sh <pr-number> [--sha <sha>] [--image-tag T] [--base-domain D] [--out <file>]" >&2
	exit 2
}

while [ $# -gt 0 ]; do
	case "$1" in
	--sha)
		SHA="${2:?--sha needs a value}"
		shift 2
		;;
	--image-tag)
		TAG="${2:?--image-tag needs a value}"
		shift 2
		;;
	--base-domain)
		DOMAIN="${2:?--base-domain needs a value}"
		shift 2
		;;
	--out)
		OUT="${2:?--out needs a value}"
		shift 2
		;;
	-h | --help)
		sed -n '3,30p' "$0"
		exit 0
		;;
	-*)
		echo "unknown option '$1'" >&2
		usage
		;;
	*)
		[ -z "$PR" ] || usage
		PR="$1"
		shift
		;;
	esac
done

[ -n "$PR" ] || usage
if ! printf '%s' "$PR" | grep -Eq '^[1-9][0-9]{0,8}$'; then
	echo "invalid PR number '$PR' (expected a positive integer without leading zeros)" >&2
	exit 2
fi

if [ -z "$TAG" ]; then
	if printf '%s' "$SHA" | grep -Eq '^[0-9a-f]{7,40}$'; then
		TAG="$(printf '%s' "$SHA" | cut -c1-7)"
	else
		echo "no --image-tag and --sha is not a hex sha: refusing to guess an image" >&2
		exit 2
	fi
fi
if ! printf '%s' "$TAG" | grep -Eq '^[0-9a-f]{7}$'; then
	echo "invalid --image-tag '$TAG' (expected 7 lower-case hex characters)" >&2
	exit 2
fi
if ! printf '%s' "$DOMAIN" | grep -Eq '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$'; then
	echo "invalid --base-domain '$DOMAIN'" >&2
	exit 2
fi

STACK="saiku-oss-pr-${PR}"
OUT="${OUT:-/tmp/${STACK}.env}"

# Hex only, so the value is safe inside an env file, a URL and a curl config
# without quoting. `openssl` when present, /dev/urandom otherwise.
rand() {
	if command -v openssl >/dev/null 2>&1; then
		openssl rand -hex "${1:-20}"
	else
		head -c "${1:-20}" /dev/urandom | od -An -tx1 | tr -d ' \n'
	fi
}

# A value from the file this run is about to overwrite, if there is one.
previous() {
	[ -f "$OUT" ] || return 0
	grep -E "^$1=" "$OUT" 2>/dev/null | head -1 | cut -d= -f2- || true
}

# Exported value > value kept from the previous render > freshly generated.
stable() {
	local name="$1" generated="$2" current kept
	current="$(printenv "$name" 2>/dev/null || true)"
	if [ -n "$current" ]; then
		printf '%s' "$current"
		return 0
	fi
	kept="$(previous "$name")"
	if [ -n "$kept" ]; then
		printf '%s' "$kept"
	else
		printf '%s' "$generated"
	fi
}

HOST_VALUE="${PREVIEW_HOST:-oss-pr-${PR}.${DOMAIN}}"
PASSWORD="$(stable SAIKU_ADMIN_PASSWORD "prevpw_$(rand 20)")"

umask 077
cat >"$OUT" <<EOF
# Generated by infra/preview/render-env.sh for PR ${PR}.
# Disposable per-stack values. 0600. Never commit, never share between PRs.
COMPOSE_PROJECT_NAME=${STACK}

# --- image: the per-SHA tag docker.yml publishes for the PR head ----------
SAIKU_IMAGE=${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${TAG}

# --- hostname (one label under the base domain: the wildcard cert covers it)
PREVIEW_HOST=${HOST_VALUE}
ORIGIN=https://${HOST_VALUE}

# --- admin identity (the launcher hashes the password at boot) ------------
PREVIEW_ADMIN_USER=admin
SAIKU_ADMIN_PASSWORD=${PASSWORD}

# --- self-check ------------------------------------------------------------
# '' = report only. Set to '--require-all' to fail the bring-up when any
# feature is inactive.
PREVIEW_SELFCHECK_ARGS=${PREVIEW_SELFCHECK_ARGS---require-all}
EOF

echo "$OUT"
