/*
 *   Copyright 2026 Spicule Ltd
 *   Apache License, Version 2.0.
 */
package org.saiku.service.snapshot;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.List;
import javax.imageio.ImageIO;

/**
 * Draws a resolved {@link Snapshot} to a single-page PNG with headless AWT (saiku#1810) — the
 * thumbnail format for channel digests (#1099).
 *
 * <p><b>No browser.</b> {@link BufferedImage} + {@link Graphics2D} is an in-memory raster; there is no
 * display, no windowing toolkit and no HTML/JS runtime involved. The renderer works under
 * {@code java.awt.headless=true} (which the launcher sets, and which is the only sane posture for a
 * server) and uses AWT's <b>logical</b> fonts ({@code SansSerif}), so it needs no font files staged
 * into the distribution and degrades to whatever the JDK maps the logical family to.
 *
 * <p>Canvas dimensions are derived from the row count and clamped to a fixed maximum, so a reference
 * with many panels cannot ask for an unbounded bitmap. Text is drawn clipped to its column and
 * ellipsised, which also means a long label degrades visually rather than overflowing the canvas.
 */
public final class PngSnapshotRenderer implements SnapshotRenderer {

    private static final int WIDTH = 800;
    private static final int MAX_HEIGHT = 4000;
    private static final int PADDING = 24;
    private static final int TITLE_HEIGHT = 40;
    private static final int META_HEIGHT = 22;
    private static final int ROW_HEIGHT = 28;
    private static final int LABEL_COLUMN = 480;

    private static final Color BACKGROUND = Color.WHITE;
    private static final Color TITLE_COLOR = new Color(0x11, 0x11, 0x11);
    private static final Color META_COLOR = new Color(0x77, 0x77, 0x77);
    private static final Color LABEL_COLOR = new Color(0x33, 0x33, 0x33);
    private static final Color VALUE_COLOR = new Color(0x00, 0x00, 0x00);
    private static final Color RULE_COLOR = new Color(0xE0, 0xE0, 0xE0);

    @Override
    public SnapshotFormat format() {
        return SnapshotFormat.PNG;
    }

    @Override
    public byte[] render(Snapshot snapshot) {
        if (snapshot == null) {
            throw new SnapshotRenderException("snapshot is required");
        }
        List<SnapshotRenderer.Snapshot.Row> rows = snapshot.rows();
        int height =
                Math.min(MAX_HEIGHT, PADDING * 2 + TITLE_HEIGHT + META_HEIGHT + Math.max(1, rows.size()) * ROW_HEIGHT);
        BufferedImage image = new BufferedImage(WIDTH, height, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = image.createGraphics();
        try {
            g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
            g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g.setColor(BACKGROUND);
            g.fillRect(0, 0, WIDTH, height);

            Font titleFont = font(Font.BOLD, 20);
            Font metaFont = font(Font.PLAIN, 12);
            Font labelFont = font(Font.BOLD, 14);
            Font valueFont = font(Font.PLAIN, 14);

            int y = PADDING;
            String title =
                    (snapshot.title() == null || snapshot.title().isBlank()) ? "Dashboard snapshot" : snapshot.title();
            g.setFont(titleFont);
            g.setColor(TITLE_COLOR);
            y = drawClipped(g, title, PADDING, y + titleFont.getSize(), WIDTH - PADDING * 2);

            g.setFont(metaFont);
            g.setColor(META_COLOR);
            String meta = "Generated by Saiku";
            y = drawClipped(g, meta, PADDING, y + metaFont.getSize() + 4, WIDTH - PADDING * 2);

            y += 8;
            g.setColor(RULE_COLOR);
            g.drawLine(PADDING, y, WIDTH - PADDING, y);

            for (SnapshotRenderer.Snapshot.Row row : rows) {
                if (y + ROW_HEIGHT > height) {
                    break; // canvas clamp: extra rows are dropped rather than overflowing
                }
                y += ROW_HEIGHT;
                g.setFont(labelFont);
                g.setColor(LABEL_COLOR);
                drawClipped(g, row.label(), PADDING, y - 8, LABEL_COLUMN);
                g.setFont(valueFont);
                g.setColor(VALUE_COLOR);
                FontMetrics fm = g.getFontMetrics();
                String value = row.value() == null ? "" : row.value();
                int valueWidth = fm.stringWidth(value);
                int maxWidth = WIDTH - PADDING * 2;
                if (valueWidth > maxWidth) {
                    value = ellipsise(value, fm, maxWidth);
                }
                g.drawString(value, WIDTH - PADDING - fm.stringWidth(value), y - 8);
            }
        } finally {
            g.dispose();
        }

        ByteArrayOutputStream out = new ByteArrayOutputStream(8 * 1024);
        try {
            if (!ImageIO.write(image, "png", out)) {
                throw new SnapshotRenderException("no PNG writer is available in this JVM");
            }
        } catch (IOException e) {
            throw new SnapshotRenderException("snapshot PNG could not be encoded", e);
        }
        byte[] bytes = out.toByteArray();
        if (bytes.length == 0) {
            throw new SnapshotRenderException("snapshot PNG encoder produced no output");
        }
        return bytes;
    }

    /**
     * A logical font, or a clear failure if this JVM has no fonts at all.
     *
     * <p>A headless JRE with no fontconfig and no font files (a bare {@code eclipse-temurin} JRE
     * base, a scratch container) throws a bare {@code RuntimeException: Fontconfig head is null} from
     * deep inside {@code sun.awt}. That surfaces to a scheduler as an unexplained FAILED run, so it
     * is translated here into a message that names the actual fix. The shipped Docker image installs
     * {@code fontconfig} + {@code fonts-dejavu-core} for exactly this reason.
     */
    private static Font font(int style, int size) {
        try {
            Font f = new Font(Font.SANS_SERIF, style, size);
            // new Font() itself does not touch the font system; the first getFontMetrics() does, and
            // that is where a fontless JVM blows up. Probe with a throwaway 1x1 raster so the
            // failure is raised here, with a message that names the fix, rather than mid-draw.
            BufferedImage probe = new BufferedImage(1, 1, BufferedImage.TYPE_INT_RGB);
            Graphics2D pg = probe.createGraphics();
            try {
                pg.getFontMetrics(f);
            } finally {
                pg.dispose();
            }
            return f;
        } catch (RuntimeException | Error e) {
            throw new SnapshotRenderException("snapshot PNG rendering needs at least one font available to the JVM", e);
        }
    }

    /** Draws {@code text} clipped to {@code maxWidth} px, ellipsising with a trailing "…". */
    private static int drawClipped(Graphics2D g, String text, int x, int baselineY, int maxWidth) {
        if (text == null || text.isEmpty()) {
            return baselineY;
        }
        FontMetrics fm = g.getFontMetrics();
        g.drawString(ellipsise(text, fm, maxWidth), x, baselineY);
        return baselineY;
    }

    private static String ellipsise(String text, FontMetrics fm, int maxWidth) {
        if (maxWidth <= 0) {
            return "";
        }
        if (fm.stringWidth(text) <= maxWidth) {
            return text;
        }
        String ellipsis = "…";
        int budget = maxWidth - fm.stringWidth(ellipsis);
        if (budget <= 0) {
            return "";
        }
        int end = text.length();
        while (end > 0 && fm.stringWidth(text.substring(0, end)) > budget) {
            end--;
        }
        return text.substring(0, end) + ellipsis;
    }
}
